/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f4',
        'on-background': '#1c1c19',
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#414944',
        outline: '#717974',
        'outline-variant': '#c0c8c3',
        primary: '#00261b',
        'on-primary': '#ffffff',
        'primary-container': '#0b3d2e',
        'primary-fixed': '#bcedd7',
        'on-primary-fixed': '#002116',
        secondary: '#7c563b',
        'on-secondary': '#ffffff',
        'secondary-container': '#fecaa8',
        'secondary-fixed': '#ffdcc6',
        'on-secondary-fixed': '#2f1502',
        tertiary: '#735c00',
        'tertiary-container': '#cba72f',
        'tertiary-fixed': '#ffe088',
        'on-tertiary-fixed': '#241a00',
        clay: '#A44A3F',
        'deep-forest': '#0B3D2E',
        'earth-brown': '#3C2F2F',
        'warm-gold': '#D4AF37',
        ivory: '#FFFFF0',
      },
      fontFamily: {
        serif: ['Noto Serif', 'serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Noto Serif', 'serif'],
        headline: ['Noto Serif', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
      },
    },
  },
  plugins: [],
}
